image:
  repository: artifactory.dagility.com/docker/project_for_sl1-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: project_for_sl1-frontend-default.dagility.com
    paths:
    - /
serviceAccount:
  create: false
